LearnMSSQL/Controllers/TestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LearnMSSQL.ViewModels;
using Microsoft.AspNet.Identity;
using LearnMSSQL.Models;



namespace LearnMSSQL.Controllers
{
    public class TestsController : Controller
    {
        //Connection with database

        private ApplicationDbContext _context;

        public TestsController()
        {
            _context = new ApplicationDbContext();
        }

        //Disposal of DbContext, which is a disposable object

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult Test1()
        {
            return View();
        }

        public ActionResult Test2()
        {
            return View();
        }

        public ActionResult Test3()
        {
            return View();
        }

        public ActionResult Test4()
        {
                return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ResultsCalculation(ResultsViewModel viewModel)
        {
              // Validate user has replied to all questions in the Test.
              // If not, return the same page with the answers he provided.
            

            if (!ModelState.IsValid)
            {

                if (viewModel.TestTaken == "Test 1")
                {
                    return View("Test1", viewModel);
                }
                else if (viewModel.TestTaken == "Test 2")
                {
                    return View("Test2", viewModel);
                }
                    
                else if (viewModel.TestTaken == "Test 3")
                {
                    return View("Test3", viewModel);
                }
                else if (viewModel.TestTaken == "Test 4")
                {
                    return View("Test4", viewModel);
                }

            }

            //Calculate the Grade for the Test that was submitted

            var FinalGrade = 0;

            if (viewModel.Answer1 == true)
                FinalGrade += 10;
            if (viewModel.Answer2 == true)
                FinalGrade += 10;
            if (viewModel.Answer3 == true)
                FinalGrade += 10;
            if (viewModel.Answer4 == true)
                FinalGrade += 10;
            if (viewModel.Answer5 == true)
                FinalGrade += 10;
            if (viewModel.Answer6 == true)
                FinalGrade += 10;
            if (viewModel.Answer7 == true)
                FinalGrade += 10;
            if (viewModel.Answer8 == true)
                FinalGrade += 10;
            if (viewModel.Answer9 == true)
                FinalGrade += 10;
            if (viewModel.Answer10 == true)
                FinalGrade += 10;


            //Get Id of the current logged in user
            var CurrentUserId = User.Identity.GetUserId();

            //The following logic is applied for all 4 Tests

            //Check which Test the user submitted
            if (viewModel.TestTaken == "Test 1")
            {
                //Search the database to find if the currently logged in user has already submitted this Test in the past
                var TestRecord = _context.MyResults.SingleOrDefault(c => c.TestName == "Test 1" && c.UserID == CurrentUserId);

                //If not, created and add a new record in the table MyResults,
                //including the current Datetime and the calculated Grade
                if (TestRecord == null)
                {
                    var NewTestRecord = new MyResults
                    {
                        UserID = CurrentUserId,
                        TestName = "Test 1",
                        TestSubject = "Microsoft SQL Server Basics",
                        Difficulty = "Beginner",
                        Time = DateTime.Now,
                        Grade = FinalGrade
                    };

                    _context.MyResults.Add(NewTestRecord);

                }
                //If the user has already submitted this test in the past, 
                //update the database record with the current Datetime and the new Grade
                else
                {

                    TestRecord.Time = DateTime.Now;
                    TestRecord.Grade = FinalGrade;

                }

            }
            else if (viewModel.TestTaken == "Test 2")
            {

                var TestRecord = _context.MyResults.SingleOrDefault(c => c.TestName == "Test 2" && c.UserID == CurrentUserId);

                if (TestRecord == null)
                {
                    var NewTestRecord = new MyResults
                    {
                        UserID = CurrentUserId,
                        TestName = "Test 2",
                        TestSubject = "Microsoft SQL Server Advanced",
                        Difficulty = "Student",
                        Time = DateTime.Now,
                        Grade = FinalGrade
                    };

                    _context.MyResults.Add(NewTestRecord);

                }
                else
                {

                    TestRecord.Time = DateTime.Now;
                    TestRecord.Grade = FinalGrade;

                }

            }
            else if (viewModel.TestTaken == "Test 3")
            {

                var TestRecord = _context.MyResults.SingleOrDefault(c => c.TestName == "Test 3" && c.UserID == CurrentUserId);

                if (TestRecord == null)
                {
                    var NewTestRecord = new MyResults
                    {
                        UserID = CurrentUserId,
                        TestName = "Test 3",
                        TestSubject = "Microsoft SQL Server Master",
                        Difficulty = "Master",
                        Time = DateTime.Now,
                        Grade = FinalGrade
                    };

                    _context.MyResults.Add(NewTestRecord);

                }
                else
                {

                    TestRecord.Time = DateTime.Now;
                    TestRecord.Grade = FinalGrade;

                }

            }
            else if (viewModel.TestTaken == "Test 4")
            {

                var TestRecord = _context.MyResults.SingleOrDefault(c => c.TestName == "Test 4" && c.UserID == CurrentUserId);

                if (TestRecord == null)
                {
                    var NewTestRecord = new MyResults
                    {
                        UserID = CurrentUserId,
                        TestName = "Test 4",
                        TestSubject = "Microsoft SQL Server Professor",
                        Difficulty = "Professor",
                        Time = DateTime.Now,
                        Grade = FinalGrade
                    };

                    _context.MyResults.Add(NewTestRecord);

                }
                else
                {

                    TestRecord.Time = DateTime.Now;
                    TestRecord.Grade = FinalGrade;

                }

            }

            //Save changes to the database
            _context.SaveChanges();

            //Redirect to MyResults page
            return RedirectToAction("Index", "MyResults");


        }

    }
}

LearnMSSQL/Views/Tests/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />

<div style="text-align:center">

    <p style="font-size:135%;" class="btn-lg btn-primary">
    Take a look at all the available Tests and choose the one that better fits your needs
    </p>

</div>

<br />


<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Name</th>
            <th>Subject</th>
            <th>Difficulty</th>
            <th>Description</th>

        </tr>
    </thead>
    <tbody>
            <tr>
                <td align="center" width="90px" style="font-size:125%">
                @Html.ActionLink("Test 1", "Test1", "Tests")       
                </td>
                <td>Microsoft SQL Server Basics</td>
                <td>Beginner</td>
                <td>
                    This is your first step torwards success. A combination of low difficulty questions, 
                    with the purpose of ensuring you have understood all the basics of MSSQL. 
                </td>
                
            </tr>

            <tr>
                <td align="center" width="90px" style="font-size:125%">
                    @Html.ActionLink("Test 2", "Test2", "Tests")
                </td>
                <td>Microsoft SQL Server Advanced</td>
                <td>Student</td>
                <td>
                    You're officialy a student now. You already mastered all the basic information and you'are ready start digging dipper into
                    the well of knowledge and sharpen your skills.
                </td>
            </tr>

            <tr>
                <td align="center" width="90px" style="font-size:125%">
                    @Html.ActionLink("Test 3", "Test3", "Tests")
                </td>
                <td>Microsoft SQL Server Master</td>
                <td>Master</td>
                <td>
                    A true MSSQL Master! You have come so far and you won't stop now. Time to push yourself to the limit
                    and gain truly advanced knowledge on all topics.
                </td>
            </tr>

            <tr>
                <td align="center" width="90px" style="font-size:125%">
                    @Html.ActionLink("Test 4", "Test4", "Tests")
                </td>
                <td>Microsoft SQL Server Professor</td>
                <td>Professor</td>
                <td>
                    Let's be honest with each other. This is a test that only the creator of SQL Server and a handful of people 
                    can pass. If you score well on this one, well, you're the Professor from now on!
                </td>
            </tr>
    </tbody>
</table>

LearnMSSQL/Views/Tests/Test1.cshtml
@model LearnMSSQL.ViewModels.ResultsViewModel
@{
    ViewBag.Title = "Test1";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<br />
<br />

<div style="text-align:center">

    <p style="font-size:160%;" class="btn-lg btn-primary">Test 1 - Microsoft SQL Server Basics</p>

</div>

<br />

<div class="jumbotron" style="font-size:140%">


    @using (Html.BeginForm("ResultsCalculation", "Tests"))
    {

        //Store hidden value with the name of the test
        @Html.HiddenFor(m => m.TestTaken, new { Value = "Test 1" })

        //Apply antiforgerytoken for security
        @Html.AntiForgeryToken()

        <div>@Html.ValidationSummary(true, "Please answer all questions before you submit the Test!")</div>

        <div class="form-group">

            @*Based on the answer of the user, store true if the answer is correct, else store false *@
            <label style="font-weight:bold">What is normalization?</label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer1)
            <br />
            @Html.RadioButtonFor(m => m.Answer1, true) It is a set of database design rules to minimize redundancy.
            <br />
            @Html.RadioButtonFor(m => m.Answer1, false) It is a set of rules to normalize database transactions.
            <br />
            @Html.RadioButtonFor(m => m.Answer1, false) It is a set of rules to improve database performance.


        </div>

        <br />

        <div class="form-group">

            <label style="font-weight:bold">ACID stands for _______.</label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer2)
            <br />
            @Html.RadioButtonFor(m => m.Answer2, false) Atomic, Cryptic, Independent, Durable
            <br />
            @Html.RadioButtonFor(m => m.Answer2, true) Atomicity, Consistency, Isolation, Durability
            <br />
            @Html.RadioButtonFor(m => m.Answer2, false) Automatic, Concurrent, Isolation, Durability

        </div>

        <br />

        <div class="form-group">

            <label style="font-weight:bold">What is Primary Key?</label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer3)
            <br />
            @Html.RadioButtonFor(m => m.Answer3, false) Primary keys are unique names of a table.
            <br />
            @Html.RadioButtonFor(m => m.Answer3, false) Primary keys are integer ids in a table rows.
            <br />
            @Html.RadioButtonFor(m => m.Answer3, true) Primary keys are unique identifiers for each row in a table.

        </div>

        <br />

        <div class="form-group">

            <label style="font-weight:bold">A table can have more than one combination of columns that uniquely identify the row in a table; each combination is called_________.</label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer4)
            <br />
            @Html.RadioButtonFor(m => m.Answer4, false) Foreign Key
            <br />
            @Html.RadioButtonFor(m => m.Answer4, true) Candidate Key
            <br />
            @Html.RadioButtonFor(m => m.Answer4, false) Composite Key

        </div>

        <br />

        <div class="form-group">

            <label style="font-weight:bold">A column that automatically generates numeric values is called __________.</label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer5)
            <br />
            @Html.RadioButtonFor(m => m.Answer5, false) Unique column
            <br />
            @Html.RadioButtonFor(m => m.Answer5, false) Integer column
            <br />
            @Html.RadioButtonFor(m => m.Answer5, true) Identity column

        </div>

        <br />

        <div class="form-group">

            <label style="font-weight:bold">What is the correct order of query operators in a SQL query?</label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer6)
            <br />
            @Html.RadioButtonFor(m => m.Answer6, true) SELECT -> FROM -> OUTER -> WHERE
            <br />
            @Html.RadioButtonFor(m => m.Answer6, false) FROM -> OUTER -> WHERE -> ON
            <br />
            @Html.RadioButtonFor(m => m.Answer6, false) SELECT -> FROM -> WHERE -> OUTER

        </div>

        <br />

        <div class="form-group">

            <label style="font-weight:bold">What are indexes?</label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer7)
            <br />
            @Html.RadioButtonFor(m => m.Answer7, true) Index speed up the data retrieval
            <br />
            @Html.RadioButtonFor(m => m.Answer7, false) Index stores large number of integer values
            <br />
            @Html.RadioButtonFor(m => m.Answer7, false) Index minimize the data redundancy

        </div>

        <br />

        <div class="form-group">

            <label style="font-weight:bold">How many types of indexes in SQL server?</label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer8)
            <br />
            @Html.RadioButtonFor(m => m.Answer8, false) Integer and string
            <br />
            @Html.RadioButtonFor(m => m.Answer8, false) Unique and non-unique
            <br />
            @Html.RadioButtonFor(m => m.Answer8, true) Clustered and Nonclustered

        </div>

        <br />

        <div class="form-group">

            <label style="font-weight:bold">RAID stands for ________.</label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer9)
            <br />
            @Html.RadioButtonFor(m => m.Answer9, false) Reduce Array of Independent Disks
            <br />
            @Html.RadioButtonFor(m => m.Answer9, true) Redundant Array of Independent Disks
            <br />
            @Html.RadioButtonFor(m => m.Answer9, false) Redundant Automatic Individual Durable

        </div>

        <br />

        <div class="form-group">

            <label style="font-weight:bold">What is the difference between Primary key and Unique key?</label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer10)
            <br />
            @Html.RadioButtonFor(m => m.Answer10, false) Primary key doesn’t allow null value whereas unique key allows multiple null values.
            <br />
            @Html.RadioButtonFor(m => m.Answer10, false) Primary key allows one null value whereas unique key doesn’t allow null value.
            <br />
            @Html.RadioButtonFor(m => m.Answer10, true) Primary key doesn’t allow null value whereas unique key allows one null value.

        </div>

        <br />

        <button type="submit" class="btn btn-primary" style="font-size:92%">Submit</button>

    }

</div>

LearnMSSQL/Views/Tests/Test2.cshtml
@model LearnMSSQL.ViewModels.ResultsViewModel
@{
    ViewBag.Title = "Test2";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />

<div style="text-align:center">

    <p style="font-size:160%;" class="btn-lg btn-primary">Test 2 - Microsoft SQL Server Advanced</p>

</div>

<br />

<div class="jumbotron" style="font-size:140%">


    @using (Html.BeginForm("ResultsCalculation", "Tests"))
    {

        //Store hidden value with the name of the test
        @Html.HiddenFor(m => m.TestTaken, new { Value = "Test 2" })

        //Apply antiforgerytoken for security
        @Html.AntiForgeryToken()

        <div>@Html.ValidationSummary(true, "Please answer all questions before you submit the Test!")</div>

        <div class="form-group">

            @*Based on the answer of the user, store true if the answer is correct, else store false *@
            <label style="font-weight:bold">OLTP stands for _________.</label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer1)
            <br />
            @Html.RadioButtonFor(m => m.Answer1, true) Online Transaction Processing
            <br />
            @Html.RadioButtonFor(m => m.Answer1, false) Offline Transaction Processing
            <br />
            @Html.RadioButtonFor(m => m.Answer1, false) Ontime Transaction Program


        </div>

        <br />

        <div class="form-group">

            <label style="font-weight:bold">Which of the followings are the types of locks in SQL Server?</label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer2)
            <br />
            @Html.RadioButtonFor(m => m.Answer2, false) Shared locks
            <br />
            @Html.RadioButtonFor(m => m.Answer2, false) Exclusive locks
            <br />
            @Html.RadioButtonFor(m => m.Answer2, true) All of the above

        </div>

        <br />

        <div class="form-group">

            <label style="font-weight:bold">What are the authentication modes in SQL Server?</label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer3)
            <br />
            @Html.RadioButtonFor(m => m.Answer3, false) Windows mode
            <br />
            @Html.RadioButtonFor(m => m.Answer3, false) Mixed mode
            <br />
            @Html.RadioButtonFor(m => m.Answer3, true) All of the above

        </div>

        <br />

        <div class="form-group">

            <label style="font-weight:bold">What is a trigger?</label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer4)
            <br />
            @Html.RadioButtonFor(m => m.Answer4, true) A trigger is a SQL procedure that initiates an action when an event (INSERT, DELETE or UPDATE) occurs.
            <br />
            @Html.RadioButtonFor(m => m.Answer4, false) A trigger is an event that can be raised from Stored Procedures.
            <br />
            @Html.RadioButtonFor(m => m.Answer4, false) A trigger is a SQL procedure that performs some tasks on accessing db tables.

        </div>

        <br />

        <div class="form-group">

            <label style="font-weight:bold">What are the different types of trigger</label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer5)
            <br />
            @Html.RadioButtonFor(m => m.Answer5, false) DDL and DCL
            <br />
            @Html.RadioButtonFor(m => m.Answer5, false) DDL and DUL
            <br />
            @Html.RadioButtonFor(m => m.Answer5, true) DML and DDL

        </div>

        <br />

        <div class="form-group">

            <label style="font-weight:bold">What are the different types of temporary tables in SQL server?</label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer6)
            <br />
            @Html.RadioButtonFor(m => m.Answer6, false) Indexed and non-index temporary tables
            <br />
            @Html.RadioButtonFor(m => m.Answer6, true) Global and local temporary tables
            <br />
            @Html.RadioButtonFor(m => m.Answer6, false) Unique and shared temporary tables

        </div>

        <br />

        <div class="form-group">

            <label style="font-weight:bold">Which of the following is not a valid data type in SQL server?</label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer7)
            <br />
            @Html.RadioButtonFor(m => m.Answer7, true) blob
            <br />
            @Html.RadioButtonFor(m => m.Answer7, false) nvarchar
            <br />
            @Html.RadioButtonFor(m => m.Answer7, false) xml

        </div>

        <br />

        <div class="form-group">

            <label style="font-weight:bold">Which of the followings are valid Transaction levels in SQL Server?</label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer8)
            <br />
            @Html.RadioButtonFor(m => m.Answer8, false) READ COMMITTED
            <br />
            @Html.RadioButtonFor(m => m.Answer8, false) REPEATABLE READ
            <br />
            @Html.RadioButtonFor(m => m.Answer8, true) All of the above


        </div>

        <br />

        <div class="form-group">

            <label style="font-weight:bold">Which of the following keyword is used to raise an error in stored procedure?</label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer9)
            <br />
            @Html.RadioButtonFor(m => m.Answer9, false) THROW
            <br />
            @Html.RadioButtonFor(m => m.Answer9, false) THROWERROR
            <br />
            @Html.RadioButtonFor(m => m.Answer9, true) RAISEERROR

        </div>

        <br />

        <div class="form-group">

            <label style="font-weight:bold">What are the different types of replication available in SQL server?</label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer10)
            <br />
            @Html.RadioButtonFor(m => m.Answer10, false) All of the below
            <br />
            @Html.RadioButtonFor(m => m.Answer10, true) Transactional Replication
            <br />
            @Html.RadioButtonFor(m => m.Answer10, false) Merge Replication

        </div>

        <br />

        <button type="submit" class="btn btn-primary" style="font-size:92%">Submit</button>

    }

</div>

LearnMSSQL/Views/Tests/Test3.cshtml
@model LearnMSSQL.ViewModels.ResultsViewModel
@{
    ViewBag.Title = "Test3";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />

<div style="text-align:center">

    <p style="font-size:160%;" class="btn-lg btn-primary">Test 3 - Microsoft SQL Server Master</p>

</div>

<br />

<div class="jumbotron" style="font-size:140%">


    @using (Html.BeginForm("ResultsCalculation", "Tests"))
    {

        //Store hidden value with the name of the test
        @Html.HiddenFor(m => m.TestTaken, new { Value = "Test 3" })

        //Apply antiforgerytoken for security
        @Html.AntiForgeryToken()

        <div>@Html.ValidationSummary(true, "Please answer all questions before you submit the Test!")</div>

        <div class="form-group">

            @*Based on the answer of the user, store true if the answer is correct, else store false *@
            <label style="font-weight:bold">
                Assuming UserProfile is a table containing a column Proession which accepts NULL value. What is the result of the below query.
                SET ANSI_NULLS OFF SELECT Profession FROM UserProfile WHERE (Profession <> NULL)
            </label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer1)
            <br />
            @Html.RadioButtonFor(m => m.Answer1, false) Gives an error.
            <br />
            @Html.RadioButtonFor(m => m.Answer1, true)  Returns all Professions which has not null values.
            <br />
            @Html.RadioButtonFor(m => m.Answer1, false) <> is not an operator in SQL Server.


        </div>

        <br />

        <div class="form-group">

            <label style="font-weight:bold">What is the result of the below query: SELECT SUBSTRING('DOTNET', 1, 3) AS 'Substring'</label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer2)
            <br />
            @Html.RadioButtonFor(m => m.Answer2, true) DOT
            <br />
            @Html.RadioButtonFor(m => m.Answer2, false) OTN
            <br />
            @Html.RadioButtonFor(m => m.Answer2, false) OT

        </div>

        <br />

        <div class="form-group">

            <label style="font-weight:bold">Which of the following is true about the SERIALIZABLE isolation level ?</label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer3)
            <br />
            @Html.RadioButtonFor(m => m.Answer3, false) It protects against phantom reads.
            <br />
            @Html.RadioButtonFor(m => m.Answer3, true)  It causes the highest level of contention.
            <br />
            @Html.RadioButtonFor(m => m.Answer3, false) All of the above.

        </div>

        <br />

        <div class="form-group">

            <label style="font-weight:bold">What is the result of the query: SELECT PATINDEX('DOT%', 'DOTNET') AS 'Index'</label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer4)
            <br />
            @Html.RadioButtonFor(m => m.Answer4, true) 0
            <br />
            @Html.RadioButtonFor(m => m.Answer4, false) 1
            <br />
            @Html.RadioButtonFor(m => m.Answer4, false) -1

        </div>

        <br />

        <div class="form-group">

            <label style="font-weight:bold">The SELECT statement must include which of the following clause:</label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer5)
            <br />
            @Html.RadioButtonFor(m => m.Answer5, false) SELECT clause
            <br />
            @Html.RadioButtonFor(m => m.Answer5, false) FROM clause
            <br />
            @Html.RadioButtonFor(m => m.Answer5, true) Both A and B.

        </div>

        <br />

        <div class="form-group">

            <label style="font-weight:bold">Which of the following is true?</label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer6)
            <br />
            @Html.RadioButtonFor(m => m.Answer6, false) BUILT-IN functions in SQL Server are Nondeterministic.
            <br />
            @Html.RadioButtonFor(m => m.Answer6, false) ISNULL function in SQL Server is Deterministic.
            <br />
            @Html.RadioButtonFor(m => m.Answer6, true) All of the above.

        </div>

        <br />

        <div class="form-group">

            <label style="font-weight:bold">Which of the following is true?</label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer7)
            <br />
            @Html.RadioButtonFor(m => m.Answer7, true) NULL values are included for all the aggregate functions.
            <br />
            @Html.RadioButtonFor(m => m.Answer7, false) NULL values are ignored for all the aggregate functions.
            <br />
            @Html.RadioButtonFor(m => m.Answer7, false) Both A and B.

        </div>

        <br />

        <div class="form-group">

            <label style="font-weight:bold">
                Assuming UserProfile is a table with PKUserId int, Profession Varchar(50)columns. What is the result of the below query: SELECT PKUserId,Profession  FROM UserProfile
                WHERE Profession = 'Engineer' AND (PKUserId > 12 OR PKUserId = 1)
            </label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer8)
            <br />
            @Html.RadioButtonFor(m => m.Answer8, true) Displays Users with Profession as 'engineer' with PKUserId > 12 as well as the users with PKUserId of 1.
            <br />
            @Html.RadioButtonFor(m => m.Answer8, false) Displays Users with Profession as 'engineer' with PKUserId > 12 only.
            <br />
            @Html.RadioButtonFor(m => m.Answer8, false) Displays Users with Profession as 'engineer' with PKUserId of 1 only.

        </div>

        <br />

        <div class="form-group">

            <label style="font-weight:bold">
                BEGIN TRANSACTION INSERT INTO DemoTable VALUES(5,'XYZ','DEMO'); BEGIN TRANSACTION UPDATE DemoTable SET Col3 = 'Test' WHERE TestID = 5; COMMIT TRANSACTION; ROLLBACK;
                What is the result of the above code execution?
            </label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer9)
            <br />
            @Html.RadioButtonFor(m => m.Answer9, false) The data is rolled back to the transaction starting on line1.
            <br />
            @Html.RadioButtonFor(m => m.Answer9, false) The inserted row does not exist in the table.
            <br />
            @Html.RadioButtonFor(m => m.Answer9, true) All of the above.

        </div>

        <br />

        <div class="form-group">

            <label style="font-weight:bold">How many transactions at a time can obtain an update lock on a resource?</label>
            <br />
            @Html.ValidationMessageFor(m => m.Answer10)
            <br />
            @Html.RadioButtonFor(m => m.Answer10, true) 1
            <br />
            @Html.RadioButtonFor(m => m.Answer10, false) 2
            <br />
            @Html.RadioButtonFor(m => m.Answer10, false) 3

        </div>

        <br />

        <button type="submit" class="btn btn-primary" style="font-size:92%">Submit</button>

    }

</div>